In [2]:
%reload_ext autoreload
%autoreload 2

In [3]:
from pathlib import Path

import git

repo = git.Repo(Path(".").absolute(), search_parent_directories=True)
ROOT = Path(repo.working_tree_dir)

In [4]:
cd $ROOT

/scratch/scmjhl1/Documents/capturing-word-order


In [5]:
import logging
import pickle

import numpy as np
import torch
from tqdm.auto import tqdm

from src.misc import WV, process_word_vecs

In [6]:
FAST_TEXT = ROOT / "data/raw/crawl-300d-2M.vec"

In [7]:
word2index, word_vecs = process_word_vecs(FAST_TEXT)

In [8]:
wv = WV(word_vecs.float(), word2index)

In [9]:
wv.vecs

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.0282, -0.0557, -0.0451,  ..., -0.0370, -0.0725, -0.0042],
        [ 0.0231,  0.0170,  0.0157,  ...,  0.0744, -0.1118,  0.0963],
        ...,
        [-0.0220, -0.5017,  0.2547,  ..., -0.2723, -0.4114,  0.0499],
        [ 0.1029, -0.0357,  0.2598,  ...,  0.0879,  0.1195, -0.3743],
        [ 0.5513,  0.0287,  0.1653,  ..., -0.1665, -0.0714,  0.3548]])

In [49]:
diff = BigramFunction("diff")
mult = BigramFunction("mult")

In [69]:
bigram_sents_diff = diff(torch.tensor([[[1, 2], [2, 3], [3, 4], [0, 0]]]).float())
bigram_sents_mult = mult(torch.tensor([[[1, 2], [2, 3], [3, 4], [0, 0]]]).float())

In [70]:
bigram_sents_diff

tensor([[[1., 1.],
         [1., 1.],
         [-0., -0.]]])

In [71]:
bigram_sents_mult

tensor([[[ 2.,  6.],
         [ 6., 12.],
         [ 0.,  0.]]])

In [14]:
import humanize

default_outdir = ROOT / "data" / "processed"

n_sents = 1000000
out_file_name = "wiki_{}.pkl".format(
    "_".join(humanize.intword(n_sents, format="%.0f").split())
)

In [15]:
with open(default_outdir / out_file_name, "rb") as f:
    wiki_corpus = pickle.load(f)

In [73]:
wv.to_ix_sents(wiki_corpus[:3])

tensor([[15498, 28605, 19111,    20, 15498, 28605, 19111,     9,     7, 14364,
          7042,   254,  2348,     2, 11505,  3488,     2,   357,     6, 15498,
             3],
        [39945,   167,    26,    25,    23,   425,     4,  6897,   138,  3335,
             8,   775,     3,     0,     0,     0,     0,     0,     0,     0,
             0],
        [   79,     9,     2,  1843, 14364, 12749,   932,     8,   775,    33,
           962,  1447,     4,   330,     6,  4936,     3,     0,     0,     0,
             0]])

In [74]:
diff = BigramFunction("diff")

In [79]:
mult(wv.vecs[wv.to_ix_sents(wiki_corpus[:3])])

tensor([[[ 8.7628e-02,  4.9923e-02,  5.8226e-02,  ..., -4.8766e-02,
          -9.2393e-03,  1.5590e-02],
         [-7.1577e-02, -4.4215e-02, -1.3976e-01,  ...,  5.2037e-02,
           2.5610e-04,  2.9295e-02],
         [ 1.1253e-02,  3.2287e-02,  3.1387e-02,  ...,  7.7223e-02,
           3.5750e-05,  1.1421e-02],
         ...,
         [-2.1651e-03, -1.4372e-02, -5.2834e-03,  ...,  5.1744e-04,
           3.8394e-03,  5.1168e-04],
         [-3.8380e-03, -5.8669e-03, -6.4353e-03,  ...,  6.4557e-03,
           1.2663e-03,  9.7662e-04],
         [ 3.4300e-02,  9.0094e-03, -6.5998e-03,  ..., -5.8688e-04,
          -1.1115e-03, -1.4530e-03]],

        [[-3.7822e-02, -2.5061e-02,  5.0765e-02,  ...,  2.0814e-02,
           1.5200e-02, -2.7862e-02],
         [ 1.4851e-02, -7.0797e-03, -4.5410e-03,  ...,  1.2895e-02,
           7.5780e-03, -5.7696e-04],
         [ 1.8619e-02, -9.9576e-03,  3.5998e-03,  ..., -2.5097e-03,
          -2.0203e-02,  2.3280e-04],
         ...,
         [ 0.0000e+00,  0

In [81]:
import torch.nn as nn

In [82]:
class BaselineBigram(nn.Module):
    def __init__(self, word_vecs, bigram_combiner, dist_fn, postprocessing=None):
        super(BaselineBigram, self).__init__()
        self.bigram_combiner = diffvec
        self.word_vecs = word_vecs
        self.dist_fn = dist_fn
        self.postprocessing = postprocessing

    def forward(self, sentence_ixs_batch, aggregation=True):
        """
        Transforms a sentence to either a bigram sentence vector or a sequence of bigram vectors.
        """
        out = self.bigram_combiner(self.word_vecs[sentence_ixs_batch])
        if self.postprocessing:
            out = self.postprocessing(out)
        if aggregation == True:
            out = torch.mean(out, dim=1)
        return out

In [12]:
def analyze_bigram_encoding():
    accuracy = 0.0
    
    return accuracy

In [85]:
def test_bigram(
    model,
    X,
    n_epochs,
    batch_size,
    window_size=1,
    output_dists=False,
    seed=0,
    device=device,
):
    dist = model.dist
    n_correct = 0
    n_comparisons = 0
    xs_pos = torch.tensor([], device=device)
    xs_neg = torch.tensor([], device=device)
    with torch.no_grad():
        for epoch in range(n_epochs):
            for i in range(0, X.size(0), batch_size):
                X_batch = X[i : i + batch_size]
                pos_bigram_ixs = gen_pos_bigram_ixs(X_batch)
                neg_bigram_ixs = gen_neg_bigram_ixs(X_batch)
                #                 neg_bigram_ixs = gen_rand_bigram_ixs(X_batch)
                valid_ixs = (neg_bigram_ixs[:, 1] - neg_bigram_ixs[:, 0] < 1) | (
                    neg_bigram_ixs[:, 1] - neg_bigram_ixs[:, 0] > window_size
                )
                dists_pos = torch.max(
                    dist(
                        model(X_batch[valid_ixs]).unsqueeze(1),
                        model(X_batch[valid_ixs], aggregation=False),
                    ),
                    dim=2,
                    keepdim=True,
                )[0]
                dists_neg = dist(
                    model(X_batch[valid_ixs]).unsqueeze(1),
                    model(neg_bigram_ixs[valid_ixs]).unsqueeze(1),
                )

                if output_dists == True:
                    xs_pos = torch.cat(
                        (
                            xs_pos,
                            dist(
                                model(X_batch[valid_ixs]).unsqueeze(1),
                                model(pos_bigram_ixs[valid_ixs]).unsqueeze(1),
                            ),
                        ),
                        dim=0,
                    )
                    xs_neg = torch.cat((xs_neg, dists_neg), dim=0)

                result = dists_pos < dists_neg
                n_correct += torch.sum(result).item()
                n_comparisons += result.size(0)
                print(
                    "Accuracy: {:2.4f} {:2.1f}% done\r".format(
                        np.mean(n_correct / n_comparisons),
                        (epoch + (i + X_batch.size(0)) / X.size(0)) / n_epochs * 100,
                    ),
                    end="",
                )
    if output_dists == True:
        return np.mean(n_correct / n_comparisons), xs_pos.view(-1), xs_neg.view(-1)
    return np.mean(n_correct / n_comparisons)

NameError: name 'device' is not defined

In [83]:
bigram_test_params = {"X": X, "n_epochs": 1, "batch_size": 10000, "output_dists": True}

NameError: name 'X' is not defined

In [84]:
bigram_model_params = {"word_vecs": word_vecs, "dist": cos_dist}

NameError: name 'cos_dist' is not defined

In [ ]:
BaselineBigram(**bigram_model_params)

In [ ]:
result, xs_pos, xs_neg = test_bigram(
    model=BaselineBigram(**bigram_model_params), **bigram_test_params
)
print(result)
plt.hist(xs_pos, bins=1000, color="blue", alpha=0.5)
plt.hist(xs_neg, bins=1000, color="red", alpha=0.5)
plt.show()